/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAmbassadorRouteImport } from './routes/_authenticated/ambassador'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedParkRouteImport } from './routes/_authenticated/park'
import { Route as AuthenticatedPaseoVerdeRouteImport } from './routes/_authenticated/paseo-verde'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSelectParkRouteImport } from './routes/_authenticated/select-park'
import { Route as AuthenticatedSelectRoleRouteImport } from './routes/_authenticated/select-role'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmbassadorRoute = AuthenticatedAmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParkRoute = AuthenticatedParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaseoVerdeRoute = AuthenticatedPaseoVerdeRouteImport.update({
  id: '/paseo-verde',
  path: '/paseo-verde',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectParkRoute = AuthenticatedSelectParkRouteImport.update({
  id: '/select-park',
  path: '/select-park',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectRoleRoute = AuthenticatedSelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ambassador': typeof AuthenticatedAmbassadorRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/park': typeof AuthenticatedParkRoute
  '/paseo-verde': typeof AuthenticatedPaseoVerdeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/select-park': typeof AuthenticatedSelectParkRoute
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ambassador': typeof AuthenticatedAmbassadorRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/park': typeof AuthenticatedParkRoute
  '/paseo-verde': typeof AuthenticatedPaseoVerdeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/review': typeof AuthenticatedReviewRoute
  '/select-park': typeof AuthenticatedSelectParkRoute
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ambassador': typeof AuthenticatedAmbassadorRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/park': typeof AuthenticatedParkRoute
  '/_authenticated/paseo-verde': typeof AuthenticatedPaseoVerdeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/select-park': typeof AuthenticatedSelectParkRoute
  '/_authenticated/select-role': typeof AuthenticatedSelectRoleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ambassador'
    | '/applications'
    | '/home'
    | '/park'
    | '/paseo-verde'
    | '/profile'
    | '/review'
    | '/select-park'
    | '/select-role'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ambassador'
    | '/applications'
    | '/home'
    | '/park'
    | '/paseo-verde'
    | '/profile'
    | '/review'
    | '/select-park'
    | '/select-role'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ambassador'
    | '/_authenticated/applications'
    | '/_authenticated/home'
    | '/_authenticated/park'
    | '/_authenticated/paseo-verde'
    | '/_authenticated/profile'
    | '/_authenticated/review'
    | '/_authenticated/select-park'
    | '/_authenticated/select-role'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ambassador': {
      id: '/_authenticated/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AuthenticatedAmbassadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/park': {
      id: '/_authenticated/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof AuthenticatedParkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paseo-verde': {
      id: '/_authenticated/paseo-verde'
      path: '/paseo-verde'
      fullPath: '/paseo-verde'
      preLoaderRoute: typeof AuthenticatedPaseoVerdeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-park': {
      id: '/_authenticated/select-park'
      path: '/select-park'
      fullPath: '/select-park'
      preLoaderRoute: typeof AuthenticatedSelectParkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-role': {
      id: '/_authenticated/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof AuthenticatedSelectRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmbassadorRoute: typeof AuthenticatedAmbassadorRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedParkRoute: typeof AuthenticatedParkRoute
  AuthenticatedPaseoVerdeRoute: typeof AuthenticatedPaseoVerdeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSelectParkRoute: typeof AuthenticatedSelectParkRoute
  AuthenticatedSelectRoleRoute: typeof AuthenticatedSelectRoleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmbassadorRoute: AuthenticatedAmbassadorRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedParkRoute: AuthenticatedParkRoute,
  AuthenticatedPaseoVerdeRoute: AuthenticatedPaseoVerdeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSelectParkRoute: AuthenticatedSelectParkRoute,
  AuthenticatedSelectRoleRoute: AuthenticatedSelectRoleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
